---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 11390.
--- DateTime: 2026/4/1 下午3:19
---
-- KEYS[1]: 优惠券库存的 key (例如: seckill:stock:10)
-- KEYS[2]: 记录购买过该优惠券的用户集合的 key (例如: seckill:order:10)
-- ARGV[1]: 当前尝试抢购的用户 ID

local stockKey = KEYS[1]
local orderKey = KEYS[2]
local userId = ARGV[1]

-- 1. 判断库存是否充足 (get)
if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1 -- 返回 1 代表库存不足
end

-- 2. 判断用户是否已经下单 (sismember，防止一个人抢多单)
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2 -- 返回 2 代表用户已经购买过
end

-- 3. 如果能走到这里，说明有库存且没买过。开始扣库存 (decr)
redis.call('decr', stockKey)

-- 4. 将用户 ID 存入 Set 集合，记录他已经买过了 (sadd)
redis.call('sadd', orderKey, userId)

return 0 -- 返回 0 代表抢购成功！